# Anpassung vom 22.09.2026 
# Umstellung der H2-Datenbank von InMemory auf persistenten File-Modus

spring.application.name=ghostnet

server.port=8081

# Die Daten werden als Datei im Ordner data gespeichert und bleiben nach einem Neustart erhalten
spring.datasource.url=jdbc:h2:file:./data/ghostnetdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Datenbankschema wird bei bedarf aktualisiert aber nicht gelöscht
spring.jpa.hibernate.ddl-auto=update

# Datenbank-Ansicht im Browser aktivieren
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console